#!/bin/bash
File=$1
CHeaderFile=$(dirname $File)/../include/rocksdb/c.h
# Extended perf metrics live in the local C API extension header; its enum is
# recognized by the "= 1024" base value (see the header's perf-metrics block).
ExtHeaderFile=$(dirname $0)/c-api-extensions/c_api_extensions.h

echo "// **** DO NOT modify this file! ****"
echo "// This file is generated by cmd:"
echo "//   gen_perf_metrics.bash $@"
echo ""
echo "/// Rust representation of the performance metrics from RocksDB's perf_context"
echo "#[derive(Debug, Copy, Clone, PartialEq, Eq)]"
echo "#[repr(u32)]"
echo "pub enum PerfMetric {"

# Extract the metric enums and generate our enum based on that ordering:
# first the upstream enum from c.h (anchored on user_key_comparison_count),
# then the local extension enum (anchored on the 1024 base value).
perl -n0e '
if (/enum\s*\{[^}]*rocksdb_user_key_comparison_count[^}]*\}/sm
    || /enum\s*\{[^}]*rust_rocksdb_\w+\s*=\s*1024[^}]*\}/sm) {
    $enum_block = $&;

    # Extract metrics from the enum, preserving order
    @metrics = ();
    $count = 0;
    while ($enum_block =~ /(?:rust_)?rocksdb_(\w+)(?:\s*=\s*(\d+))?\s*,?/g) {
        $metric = $1;
        # If an explicit value is given, use it
        if (defined $2) {
            $count = $2;
        }
        push @metrics, [$metric, $count];
        $count++;
    }

    # Output the Rust enum variants
    foreach $pair (@metrics) {
        ($metric, $value) = @$pair;
        # Convert snake_case to PascalCase
        $name = $metric;
        $name =~ s/(^|_)(\w)/\U$2/g;
        print "    $name = $value,\n";
    }
}' $CHeaderFile $ExtHeaderFile

echo "}"
echo ""
echo "/// First discriminant served by \`rust_rocksdb_perfcontext_metric_ext\`, the"
echo "/// local C API extension covering perf-context fields that upstream's metric"
echo "/// enum lacks; smaller values go to upstream \`rocksdb_perfcontext_metric\`."
echo "/// Must match the extension enum base in c_api_extensions.h."
echo "const PERF_EXT_METRIC_BASE: u32 = 1024;"
echo ""
echo "impl PerfMetric {"
echo "    /// Returns the name of this metric as it appears in RocksDB C++"
echo "    #[allow(clippy::too_many_lines)] // one generated match arm per metric"
echo "    pub const fn name(&self) -> &'static str {"
echo "        match self {"

# Generate name mappings for metrics from both headers
perl -n0e '
if (/enum\s*\{[^}]*rocksdb_user_key_comparison_count[^}]*\}/sm
    || /enum\s*\{[^}]*rust_rocksdb_\w+\s*=\s*1024[^}]*\}/sm) {
    $enum_block = $&;

    %metric_names = ();

    # Extract metrics from the enum
    while ($enum_block =~ /(?:rust_)?rocksdb_(\w+)/g) {
        $metric = $1;
        $name = $metric;
        $name =~ s/(^|_)(\w)/\U$2/g;
        $metric_names{$name} = $metric;
    }

    # Output all mappings sorted by PascalCase name
    foreach $name (sort keys %metric_names) {
        print "            PerfMetric::$name => \"$metric_names{$name}\",\n";
    }
}' $CHeaderFile $ExtHeaderFile

echo "        }"
echo "    }"
echo "}"
echo ""
echo "impl PerfMetric {"
echo "    /// Every metric except the \`TotalMetricCount\` sentinel, in discriminant order."
echo "    pub const ALL: &[PerfMetric] = &["
perl -n0e '
if (/enum\s*\{[^}]*rocksdb_user_key_comparison_count[^}]*\}/sm
    || /enum\s*\{[^}]*rust_rocksdb_\w+\s*=\s*1024[^}]*\}/sm) {
    $enum_block = $&;
    while ($enum_block =~ /(?:rust_)?rocksdb_(\w+)(?:\s*=\s*\d+)?\s*,?/g) {
        $metric = $1;
        next if $metric eq "total_metric_count";
        $name = $metric;
        $name =~ s/(^|_)(\w)/\U$2/g;
        print "        PerfMetric::$name,\n";
    }
}' $CHeaderFile $ExtHeaderFile
echo "    ];"
echo "}"
